import type { NextPage } from 'next'
import Head from 'next/head'

import PostList from '@/components/PostList'

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hands-on basic usage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList />
    </>
  )
}

export default HomePage
