import { Suspense } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorBoundary } from 'react-error-boundary'

import LayoutCenter from '@/components/LayoutCenter'
import PostList from '@/components/PostList'
import Spinner from '@/components/Spinner'

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hands-on basic usage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutCenter>
        <ErrorBoundary
          fallbackRender={({ error }) => (
            <p className="text-3xl text-red-600">Error! {error.message}</p>
          )}
        >
          <Suspense fallback={<Spinner />}>
            <PostList />
          </Suspense>
        </ErrorBoundary>
      </LayoutCenter>
    </>
  )
}

export default HomePage
