name = "sandbox"
main = "src/index.ts"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "hono-drizzle"
database_id = "9453769b-b0ac-4a23-a043-b6c490c6ce36"
migrations_dir = "./src/db/migrations"
